### ISSUE TITLE
test

### ISSUE THREAD

**Issue by molhot** [42minirt/miniRT#29]

**Comment by molhot** [comment]
A   0.1                                              255, 255, 255

C   0,0,-2           0, 0, 1      120

L   0,0,0                        1                  255,255,255

pl   0, -10, 0      0, 1, 0                           100,0,0
pl   0,  10, 0      0, 1, 0                           100,0,0  checker 100, 50, 50

pl   -10, 0, 0      1, 0, 0                           0,100,0
pl    10, 0, 0      1, 0, 0                           0,100,0  checker 50, 100, 50

pl   0, 0, -10      0, 0, 1                           0,0,100
pl   0, 0,  10      0, 0, 1                           0,0,100  checker 50, 50, 100

co    1, 1, 0     1, 0, 0             1   1        200,200,250

なんか円錐おかしいかも？

**Comment by molhot** [comment]
A   0.1                                              255, 255, 255

C   0,2,-5           0, 0, 1      100

L   0,0,0                        1                  255,255,255

pl   0, -10, 0      0, 1, 0                           100,0,0
pl   0,  10, 0      0, 1, 0                           100,0,0  checker 100, 50, 50

pl   -10, 0, 0      1, 0, 0                           0,100,0
pl    10, 0, 0      1, 0, 0                           0,100,0  checker 50, 100, 50

pl   0, 0, -10      0, 0, 1                           0,0,100
pl   0, 0,  10      0, 0, 1                           0,0,100  checker 50, 50, 100

co    1, 1.5, 0     1, 0, 0             1   1        200,200,250
co    1, 2.5, 0     1, 1, 0             1   1        200,200,250
co    0, 3, 0     0, 1, 0             1   1		200,200,250
co    -1, 2.5, 0     -1, 1, 0             1   1		200,200,250
co    -1, 1.5, 0     -1, 0, 0             1   1        200,200,250
co    0, -3, 0     0, -1, 0             1   1		200,200,250
co    1, 0.5, 0     1, -1, 0             1   1        200,200,250
co    -1, 0.5, 0     -1, -1, 0             1   1        200,200,250

コーンなんか変。。。？

**Comment by molhot** [comment]
<img width="1440" alt="スクリーンショット 2023-06-07 17 51 54" src="https://github.com/42minirt/miniRT/assets/86003237/f1830de1-6af5-4a8b-8630-7ffbf1d4646e">

**Comment by molhot** [comment]
近くで見るとすごいいびつになっている？？

**Comment by molhot** [comment]
※描画自体弾かれる（計算が複雑すぎてわからん

**Comment by molhot** [comment]
A   0.1                                              255, 255, 255

C   0,2,-5           0, 0, 1      100

L   0,0,-2                        1                  255,255,255

pl   0, -10, 0      0, 1, 0                           100,0,0
pl   0,  10, 0      0, 1, 0                           100,0,0  checker 100, 50, 50

pl   -10, 0, 0      1, 0, 0                           0,100,0
pl    10, 0, 0      1, 0, 0                           0,100,0  checker 50, 100, 50

pl   0, 0, -10      0, 0, 1                           0,0,100
pl   0, 0,  10      0, 0, 1                           0,0,100  checker 50, 50, 100

co    1, 1.5, 0     1, 0, 0             1   1        200,200,250
co    2, 2.5, 0     0, 0, 1             1   1        200,200,250
co    -2, 2.5, 0     0, 1, 1             1   1        200,200,250
co    2, -2.5, 0     0, 1, -1             1   1        200,200,250
co    -2, -2.5, 0     0, -1, -1             1   1        200,200,250
co    1, 2.5, 0     1, 1, 0             1   1        200,200,250
co    0, 3, 0     0, 1, 0             1   1		200,200,250
co    -1, 2.5, 0     -1, 1, 0             1   1		200,200,250
co    -1, 1.5, 0     -1, 0, 0             1   1        200,200,250
co    0, -3, 0     0, -1, 0             1   1		200,200,250
co    1, 0.5, 0     1, -1, 0             1   1        200,200,250
co    -1, 0.5, 0     -1, -1, 0             1   1        200,200,250

げきおも確認ファイル（問題なさそう

**Comment by molhot** [comment]
球体は問題なさそう

**Comment by molhot** [comment]
<img width="1440" alt="スクリーンショット 2023-06-07 19 54 16" src="https://github.com/42minirt/miniRT/assets/86003237/978ecb9e-fd2d-49bf-bd93-e2fb722efa6c">
と思ったけどチョイぺちゃんこ？？

**Comment by ak0327** [comment]
```
A 0.1 255, 255, 255

C 1,1,-8 0, 0, 1 120

L 0,0,0 1 255,255,255

pl 0, -10, 0 0, 1, 0 100,0,0
pl 0, 10, 0 0, 1, 0 100,0,0 checker 100, 50, 50

pl -10, 0, 0 1, 0, 0 0,100,0
pl 10, 0, 0 1, 0, 0 0,100,0 checker 50, 100, 50

pl 0, 0, -10 0, 0, 1 0,0,100
pl 0, 0, 10 0, 0, 1 0,0,100 checker 50, 50, 100

co 1, 1, 0 1, 0, 0 1 1 200,200,250
```

**Comment by molhot** [comment]
<img width="1440" alt="スクリーンショット 2023-06-07 20 45 28" src="https://github.com/42minirt/miniRT/assets/86003237/b41b89d8-5686-4e68-8f46-f59f1b6bd079">

**Comment by ak0327** [comment]
```
# A   0.1                                              255, 255, 255
#
# C   0,0,0           0, -1, 1     160
#
# L   0,0,0                        1.0                 255,255,255
#
# pl   0, -5, 0      0, 1, 0                           255,0,0
# pl   0,  5, 0      0, 1, 0                           255,0,0  checker 200, 155, 155
#
# pl   -5, 0, 0      1, 0, 0                           0,255,0
# pl    5, 0, 0      1, 0, 0                           0,255,0  checker 155, 200, 155
#
# pl   0, 0, -5      0, 0, 1                           0,0,255
# pl   0, 0,  5      0, 0, 1                           0,0,255  checker 155, 155, 200

A 0.1 255, 255, 255

C 0,2,-5 0, 0, 1 100

L 0,0,0 1 255,255,255
# L 0,0,-5 1 255,255,255

pl 0, -10, 0 0, 1, 0 100,0,0
pl 0, 10, 0 0, 1, 0 100,0,0 checker 100, 50, 50

pl -10, 0, 0 1, 0, 0 0,100,0
pl 10, 0, 0 1, 0, 0 0,100,0 checker 50, 100, 50

pl 0, 0, -10 0, 0, 1 0,0,100
pl 0, 0, 10 0, 0, 1 0,0,100 checker 50, 50, 100

co 1, 1.5, 0    1, 0, 0 1 1 200,200,250

co 2, 2.5, 0     0, 0, 1 1 1 200,200,250

co -2, 2.5, 0   0, 1, 1 1 1 200,200,250
co 2, 0.5, 0    0, 1, -1 1 1 200,200,250

co -2, 0.5, 0   0, -1, -1 1 1 200,200,250

co 1, 2.5, 0 1, 1, 0 1 1 200,200,250
co 0, 3, 0 0, 1, 0 1 1 200,200,250
co -1, 2.5, 0 -1, 1, 0 1 1 200,200,250
co -1, 1.5, 0 -1, 0, 0 1 1 200,200,250
co 0, -3, 0 0, -1, 0 1 1 200,200,250
co 1, 0.5, 0 1, -1, 0 1 1 200,200,250
co -1, 0.5, 0 -1, -1, 0 1 1 200,200,250
```

**Comment by ak0327** [comment]
すり合わせ完了しているのでclose
